FROM node:20-alpine


ARG NODE_ENV=development
ENV NODE_ENV=$NODE_ENV
ARG PORT=8334
ENV PORT $PORT
RUN npm install -g pnpm@latest

USER node
WORKDIR /wms-api
COPY --chown=node:node package.json pnpm-lock.yaml* ./
ENV PATH /wms-api/node_modules/.bin:$PATH
COPY --chown=node:node . .
RUN pnpm install && prisma generate
CMD ["pnpm", "start:dev"]
EXPOSE $PORT
