FROM node:20-alpine
ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV
ARG PORT=8334
ENV PORT $PORT
RUN npm install -g pnpm@latest
USER node
WORKDIR /wms-api
COPY --chown=node:node package.json pnpm-lock.yaml* ./
RUN npm install
COPY --chown=node:node . .
RUN npm run prisma:generate
RUN npm run build
CMD ["pnpm", "start:prod"]
EXPOSE $PORT
