FROM node:20-alpine as api


ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV
ARG PORT=8334
ENV PORT $PORT
RUN npm install -g pnpm@latest

USER node
WORKDIR /wms-api
RUN chmod -R 777 /wms-api
COPY --chown=node:node package.json pnpm-lock.yaml* ./
ENV PATH /wms-api/node_modules/.bin:$PATH
COPY --chown=node:node . .
RUN npx rimraf dist && pnpm install --frozen-lockfile && npx prisma generate && pnpm run build
CMD ["pnpm", "start:prod"]
EXPOSE $PORT

