FROM node:20-alpine as api


ARG NODE_ENV=development
ENV NODE_ENV=$NODE_ENV
ARG PORT=8334
ENV PORT $PORT
RUN npm install -g pnpm@latest

WORKDIR /wms-api
# RUN chmod -R 777 /wms-api
COPY  package.json pnpm-lock.yaml* ./
ENV PATH /wms-api/node_modules/.bin:$PATH
COPY  . .
RUN npx rimraf dist && pnpm install && npx prisma generate
CMD ["pnpm", "start:dev"]
EXPOSE $PORT


FROM api as studio
WORKDIR /wms-studi
COPY --from=api /wms-api/prisma ./prisma
CMD ["prisma", "studio"]
EXPOSE 5555
